app/controllers/concerns/accessible.rb, app/controllers/deals_controller.rb, app/policies/deal_policy.rb, app/views/deals/index.html.erb, app/views/shared/_navbar.html.erb, app/views/shipper/shipments/index.html.erb, config/routes.rb
create shipment page for carriers and modify deal controller and policy for it
=> create shipment page for carriers and modify deal controller and policy

app/assets/stylesheets/application.scss, app/assets/stylesheets/config/_bootstrap_variables.scss, app/assets/stylesheets/config/_colors.scss, app/assets/stylesheets/config/_fonts.scss, app/assets/stylesheets/config/_reset.scss, db/schema.rb
Transferred initial css stylings from pattern library into config files.
Will proceed on front-end design of landing page next.
=> Initial transfer of css styles

app/views/pages/home.html.erb
- Typo fixed. Other body text to be developed later on.
- .svg extension added, will it work in Heroku?
=> svg-typo-fix-20171228 [done]

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/config/_reset.scss, app/assets/stylesheets/config/_variables.scss, app/assets/stylesheets/pages/_home.scss, app/views/carriers/registrations/new.html.erb, app/views/deals/index.html.erb, app/views/pages/home.html.erb, app/views/shared/_navbar.html.erb
- Navbar has been adjusted to accomodate both mobile & desktop
- NEXT: Carrier registration page
=> navbar-adj-20180103 [done]

app/assets/javascripts/jquery.autoKana.js, app/assets/javascripts/jquery.jpostal.js, app/assets/stylesheets/components/_alert.scss, app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/layouts/_section.scss, app/inputs/fake_input.rb, app/views/carriers/registrations/new.html.erb, app/views/shared/_navbar.html.erb, config/initializers/assets.rb, config/initializers/simple_form.rb, config/initializers/simple_form_bootstrap.rb, config/locales/simple_form.en.yml
- Initial front-end complete
- 「運送&保有車両」requires discussion regarding model.
- Furigana automation is more complicated than initially thought.
=> carrier-registration-20180105 [done]

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/controllers/shipments_controller.rb, app/models/pickup.rb, app/views/shipments/_pickup_fields.html.erb, app/views/shipments/_shipment_form.html.erb
- An initial branch to ensure cocoon works correctly in other environments and heroku.
=> Nested form initial 20180112

app/views/carriers/registrations/new.html.erb, app/views/shippers/registrations/new.html.erb
- h2 changed from 新規登録 to [荷主]アカウント登録
- postcode input for shipper works
- code refactored, removed autokana and notes
=> adjust-sign-in-h2-fix-postcode [done]

app/views/carriers/registrations/_vehicle_fields.html.erb, app/views/carriers/registrations/new.html.erb, app/views/shipments/_shipment_form.html.erb
- [done] initial commit to confirm cocoon funciton
- [XXX] front-end css etc
=> carrier-regist-vehicles-20180117 [done]

app/assets/javascripts/carrier_favorite_products.js
=> carrier-regist-products-count-on-load-20180117 [done]

app/assets/stylesheets/components/_form.scss, app/views/carriers/registrations/new.html.erb, app/views/shipments/_pickup_fields.html.erb, app/views/shipments/_shipment_form.html.erb
- [done] dummy for shipment form complete.
- [done] kept original form inputs back so a new shipment can still be made.
- [done] Slimmed down the inputs from the original form.
- [attention] all inputs are still a work-in-progress and are subject to change.
=> S new shipment form 20180119

app/assets/stylesheets/components/_card.scss, app/views/shipper/shipments/show.html.erb, app/views/shippers/registrations/new.html.erb
- [ON HOLD] Put on hold due to it not being a vital function as mvp.
- [note] Company explanation input (mandatory?), info that is already at hand (e.g vehicle, tel, fax?)
- [note] Upon showing the Company detail what will the Shipper want to see? Is this even necessary?
=> S-matchedCarriersDetails_20180125 [ON HOLD]

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_form.scss, app/views/shipper/shipments/quotes_req.html.erb, app/views/shipper/shipments/show.html.erb
- [done] quotation confirmation front end done
- [attention] details are still dummy will require updating upon attribute completion.
=> S-quotationConfirmation_20180126 [done]

app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/components/_form__progress.scss, app/assets/stylesheets/layouts/_section.scss, app/views/carriers/passwords/new.html.erb, app/views/carriers/sessions/new.html.erb, app/views/shipper/shipments/quotes_done.html.erb, app/views/shipper/shipments/quotes_req.html.erb, app/views/shippers/passwords/new.html.erb, app/views/shippers/sessions/new.html.erb
- [done] front-end for quotation complete page done
- [!] css names refactored to prevent too many class names.
=> S-quotationComplete_20180126 [done]

app/assets/javascripts/application.js
[NEXT] Adj design of alert a bit
=> Alert will now dissappear after x Seconds

app/assets/stylesheets/components/_navbar.scss, app/views/shipments/_shipment_form.html.erb
- Navbar avatar now works with hover, not click.
- Adj shipment start end year to begin from this year.
- Post code input on shipment form now auto fills the address.
=> postcode works on shipment form, navbar profile adj to hover

Gemfile, Gemfile.lock, Guardfile, config/environments/development.rb
How to use
- 01: Open 2 terminal tab/windows.
- 02: run `rails s` in one terminal `bundle exec guard` in the other.
- 03: Reload the website and you should see a screen like below on the terminal running guard.
- 04: Now when you make any changes the browser should reload automatically.
=> livereload added. Will local host option 127.0.0.1 cause an issue?

app/assets/stylesheets/components/_form.scss, app/views/carriers/registrations/_showNextInputs.js.erb, app/views/carriers/registrations/new.html.erb
- Use a single view to show both inputs
- Still having issues with restoring inputs after error, will attempt to fix
=> experiment Single-page Input with JavaScript

app/views/carriers/registrations/_restoreInputs.js.erb, app/views/carriers/registrations/new.html.erb
- Minor issue, since the individual values are stored, the region checkboxes are not selected.
=> Area Inputs are now restored if an error occurs.

app/views/carriers/registrations/_restoreInputs.js.erb
- Selections were made, however the input data was not sent to params upon second submission.
- Had to update the 'Original-multi-select-input' to get the data sent.
- Confirmed in console that the second submission was receving the prefecture data.
=> Prefecture Input Restoration

app/assets/stylesheets/components/_fontStyle.scss, app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/pages/_home.scss, app/views/carriers/registrations/_inputIntroduction.html.erb, app/views/carriers/registrations/new.html.erb, app/views/layouts/application.html.erb, app/views/pages/_landingCarrier.html.erb, app/views/pages/_landingShipper.html.erb
- Carrier registration page has a intro-div to mention material to prepare for a smooth sign up process.
=> Added mention of 'Material to prepare for signup'

app/assets/stylesheets/components/_button.scss, app/views/carriers/registrations/_inputAreaAndVehicles.html.erb
=> Buttons style for add/rmv vehicle adjusted

app/views/carriers/registrations/_restoreInputs.js.erb
- Country code was unnecessary since it will store individual prefectures not 全国
- Commented out region code as well. Might use it in future but the `computedName` might be an issue?
=> Debugged Restore Input

app/assets/stylesheets/components/_fontStyle.scss, app/assets/stylesheets/components/_form.scss, app/views/deals/index.html.erb
=> view upon completed carrier registration updated

app/assets/stylesheets/components/_fontStyle.scss, app/views/carriers/registrations/_inputIntroduction.html.erb, app/views/carriers/registrations/new.html.erb
- C-Registration page is rendered correctly. Minor fix to li tag.
=> Uncommented Renders on C-Regist

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_vehicleTable.scss, app/views/shipments/_carrierCard.html.erb, app/views/shipments/_matchedCarriers_onClick.js.erb, app/views/shipments/results_carrier.html.erb
- On click of Carrier, card will expand to show more details
- Vehicle table added
=> On click show carrier detail

app/views/pages/_landingNavBar.html.erb, app/views/shared/_navbar.html.erb
- Disabled 案件 related links
- Disabled Carrier related links, login and register
=> Navigation Bar Update

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/layouts/_section.scss, app/assets/stylesheets/pages/_home.scss, app/views/shared/_navbar.html.erb
- [DONE] Issue on the carrier result page.
=> Seems paragraph tag settings in `home.scss` was a global setting.
- [UNCONFIRMED] FontAwesome not showing on dashboard and register?
=> May need to check on your laptop.
- [UNCONFIRMED] Landing page doesn't fit the browser.
=> May need to check on your laptop.
=> Debug front

app/assets/stylesheets/components/_card.scss, app/views/shipments/_carrierCard.html.erb
- Carrier 運送品目 added to results.
- Carrier 運送地域　adjusted so prefecture name does not split.
=> Carrier Results Adjustments

app/views/carriers/registrations/_restoreInputs.js.erb
BEFORE
01: Select all prefectures of a certain region
02: error-submit
03: Region checkbox (not selected) => Select => Deselects all the region-prefecture inputs
AFTER
01: Select all prefectures of a certain region
02: error-submit
03: Region checkbox is now Selected
=> Prefecture Debug

app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/config/_variables.scss, app/views/layouts/application.html.erb, app/views/shared/_footer.html.erb
- As it distracts from the dashboard and registration process, currently limited to root_path.
=> Make Footer

app/assets/stylesheets/components/_form.scss
=> Adjustment To Category inputs made
